import { DailyBlock, IntercomWindow } from '@/types'

export const DAILY_BLOCKS: DailyBlock[] = [
  {
    id: 'solo-power-hour',
    startTime: '8:00 AM',
    endTime: '9:00 AM',
    title: 'Solo Power Hour',
    category: 'mortgage',
    color: '#378ADD',
    tasks: [
      'Review new leads / overnight inquiries',
      'Follow up warm leads (text/video > text only)',
      'Nurture hot prospects',
      'Pre-qualify conversations mentally',
      'Flag priority calls to book today',
    ],
  },
  {
    id: 'daily-file-huddle',
    startTime: '9:00 AM',
    endTime: '9:30 AM',
    title: 'Daily File Huddle',
    category: 'mortgage',
    color: '#378ADD',
    tasks: [
      'Review active deals',
      'Identify urgent files',
      'Flag realtor-sensitive situations',
      'Confirm assistant ownership vs your involvement',
      'Clarify anything that could trigger inbound calls',
    ],
  },
  {
    id: 'lead-conversion-block',
    startTime: '9:30 AM',
    endTime: '11:00 AM',
    title: 'Lead Conversion Block',
    category: 'mortgage',
    color: '#378ADD',
    tasks: [
      'Call new leads',
      'Follow up aged leads',
      'Respond to inbound messages',
      'Send personalized video replies where possible',
      'Book calls into 11:00–1:00 slots (or next day)',
    ],
  },
  {
    id: 'call-block',
    startTime: '11:00 AM',
    endTime: '1:00 PM',
    title: 'Call Block',
    category: 'mortgage',
    color: '#534AB7',
    tasks: [
      'Run discovery calls',
      'Build trust + educate',
      'Move leads toward application',
      'Take notes for follow-up',
      'Book next steps immediately',
    ],
  },
  {
    id: 'gym-reset',
    startTime: '1:00 PM',
    endTime: '2:00 PM',
    title: 'Gym + Reset',
    category: 'personal',
    color: '#888780',
    tasks: [
      'Workout',
      'Mentally reset',
      'No work / no calls',
    ],
  },
  {
    id: 'food-brain-break',
    startTime: '2:00 PM',
    endTime: '2:30 PM',
    title: 'Food + Brain Break',
    category: 'personal',
    color: '#888780',
    tasks: [
      'Eat',
      'Light reset (no heavy thinking)',
    ],
  },
  {
    id: 'broki-ceo-growth',
    startTime: '2:30 PM',
    endTime: '3:30 PM',
    title: 'Broki CEO – Growth',
    category: 'broki',
    color: '#534AB7',
    tasks: [
      'Follow up with trial users',
      'Close warm prospects',
      'Improve webinar funnel',
      'Reach out to 1–3 brokers',
      'Identify growth opportunities',
    ],
  },
  {
    id: 'broki-ceo-product',
    startTime: '3:30 PM',
    endTime: '4:15 PM',
    title: 'Broki CEO – Product',
    category: 'broki',
    color: '#534AB7',
    tasks: [
      'Review Intercom patterns (not just messages)',
      'Identify repeated friction points',
      'Update dev roadmap priorities',
      'Simplify one workflow',
    ],
  },
  {
    id: 'content-engine',
    startTime: '4:15 PM',
    endTime: '5:00 PM',
    title: 'Content Engine',
    category: 'content',
    color: '#3B6D11',
    tasks: [
      'Film 1–3 reels (batch if possible)',
      'Post 1 reel (personal brand)',
      'Create/post 1 static (Broki or Whiteridge)',
      'Set collabs across pages',
    ],
  },
  {
    id: 'systems-team',
    startTime: '5:00 PM',
    endTime: '5:45 PM',
    title: 'Systems + Team',
    category: 'ops',
    color: '#BA7517',
    tasks: [
      'Review assistant performance/tasks',
      'Fix 1 inefficiency in workflow',
      'Improve automation or CRM flow',
      'Delegate anything repetitive',
      'Update SOPs if needed',
    ],
  },
  {
    id: 'relationship-money',
    startTime: '5:45 PM',
    endTime: '6:30 PM',
    title: 'Relationship Money',
    category: 'referrals',
    color: '#A32D2D',
    tasks: [
      '3–5 realtor touches (text/call/video)',
      '2 past client check-ins',
      '1 new relationship started',
      'Provide value (not just checking in)',
    ],
  },
  {
    id: 'intercom-admin',
    startTime: '6:30 PM',
    endTime: '7:00 PM',
    title: 'Intercom + Admin',
    category: 'ops',
    color: '#BA7517',
    tasks: [
      'Final Intercom sweep (respond + tag patterns)',
      'Note recurring issues for product fixes',
      'Clear remaining messages',
      'Quick next-day prep (top priorities)',
    ],
  },
]

export const INTERCOM_WINDOWS: IntercomWindow[] = [
  { time: '9:30 AM', label: 'Mid-Morning Check' },
  { time: '12:30 PM', label: 'Lunch Break Sweep' },
  { time: '3:30 PM', label: 'Afternoon Pulse' },
  { time: '6:30 PM', label: 'Evening Cleanup' },
]

export const CATEGORY_COLORS: Record<string, string> = {
  mortgage: '#378ADD',
  broki: '#534AB7',
  personal: '#888780',
  content: '#3B6D11',
  ops: '#BA7517',
  referrals: '#A32D2D',
}
